### ISSUE TITLE
black 4x4 blocks appear on resized images

### ISSUE THREAD

**Issue by 0ion9** [vanyossi/artscript#82]
Recently, artscript has started replacing random 4x4 blocks of the image with black.
Here is an example:

![oold-13-archway](https://cloud.githubusercontent.com/assets/115782/8473718/d2cffc96-20ea-11e5-8957-6dd0f62dd171.png)

Note the blocks on the floor to the left, in the space below the arch, and above the arch to the right.

The original is 2545x2689 pixels. The resize settings are 'OnlyShrink' with a single size checked, '1280x1024'.

I can upload the source XCF if needed.

I have tried selecting format = jpg, and format = png. Both options have the same problem.

The positioning of the blocks appears to be random -- different blocks will be blacked-out on consecutive runs on the same image.

The problem occurs after the initial conversion to PNG using GIMP (2.8.15) is done, when it goes to shrink the image down. I have verified this by looking at the files in /tmp and seeing that they do not contain any black blocks.

`convert --version` reports:

```
Version: ImageMagick 6.9.1-4 Q16 x86_64 2015-06-03 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features:  Cipher DPC HDRI Modules OpenCL OpenMP
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms lqr ltdl lzma pangocairo png ps rsvg tiff webp wmf x xml zlib
```

**Comment by 0ion9** [comment]
I cannot currently reproduce this.
My theory is that either VirtualBox is doing something horrible that ImageMagick gets confused by, or ImageMagick fails under particularly high CPU load.

**Comment by Deevad** [comment]
Does it happen with something else than a XCF ?
XCF are converted with Gimp (command line) at first in Artscript before going to Imagemagick.

**Comment by 0ion9** [comment]
Hard to say, since I can't currently reproduce the original bug. XCF is rendering normally, and so is PNG.

**Comment by vanyossi** [comment]
Closing #invalid
Interesting bug never the less. However Artscript does not do any processing by itself, it only serves as a automatization tool.
