### ISSUE TITLE
xcf: wrong width detected, distorts output.

### ISSUE THREAD

**Issue by 0ion9** [vanyossi/artscript#85]
I just experienced a situation where artscript distorted 52 images. This seems to be because it detects the wrong input width.

GIMP shows the correct dimensions, 3502x2545:

![actualsize](https://cloud.githubusercontent.com/assets/115782/8594989/a3966686-2685-11e5-820d-cdc464e6b7a0.png)

ImageMagick also reports the correct dimensions, 3502x2545:
`storyboardish-01.xcf XCF 3502x2545 3502x2545+0+0 8-bit Grayscale sRGB 8.664MB 0.000u 0:00.000`

xcf2png also outputs a png of correct dimensions.

Artscript shows wrong dimensions, 2734x2545:
![reported-size](https://cloud.githubusercontent.com/assets/115782/8594990/a39f3a68-2685-11e5-822d-ed038d88e48c.png)

(the output size should be 50%. But 50% of 3502x2545 is 1751x1273, not the 1367x1273 artscript chooses (which is, of course, 50% of 2734x2545). Therefore, the output is distorted.)

To generate a file that causes the error, simply start GIMP 2.8 and create a new empty (white) image with dimensions 3502x2545.

I have experimented and determined that the width artscript detects is a fraction of the real width.
For example, changing size slightly to 3508x2548 causes artscript to report the dimensions as 2740x2548. 2740/3508 is 0.781.

I have tried removing my .artscriptrc and even the presets.config. Neither of these have any effect, the width is still detected wrongly.

**Comment by 0ion9** [comment]
I have just noted that artscript works correctly on the output from xcf2png. Therefore, my current workaround is to convert files to png with xcf2png, then shrink them all using artscript.

**Comment by vanyossi** [comment]
confirmed. but it only happens with particular sizes. Working on it

**Comment by 0ion9** [comment]
Yes, sorry for omitting that: it appears to occur for all images that are particularly wide (in terms of number of pixels, not image proportions). Narrow images are unaffected.

**Comment by vanyossi** [comment]
Cheking updated file for xcf spec.
https://github.com/mskala/noxcf-gimp/blob/master/devel-docs/xcf.txt

I thought maybe the general width and height would be different from the background layer but the data is the same. I'm not sure why this happens or what "file" does different to get the real size.

**Comment by vanyossi** [comment]
@0ion9 found the error. Could you test it works as expected now?

**Comment by 0ion9** [comment]
So far looks good, I'll test it a bit more extensively later :)
