### ISSUE TITLE
Complete failure to comprehend xcfs

### ISSUE THREAD

**Issue by 0ion9** [vanyossi/artscript#86]
Artscript has recently stopped doing anything remotely sensible with XCFs, just failing immediately with this error "can't read 'h'":

```
can't read "h": no such variable
can't read "h": no such variable
    while executing
"format {%dx%d} $w $h"
    (procedure "listValidate" line 55)
    invoked from within
"listValidate {typogpractice-01_04.xcf typogpractice-2.xcf typogpractice-5.xcf typogpractice-6.xcf} 1"
    ("after" script)
```

From this error, it seems most likely to me that line 407 of artscript2.tcl is failing.

Removing config files has no impact on this.
'file' and 'identify' recognize the files in question as ordinary, uncompressed xcfs and extract correct information about their dimensions. Some of them have one layer, others have more. I'm willing to provide some sample files if needed.

GIMP version: 2.8.15
TCL version: 8.6.4
Artscript version: git 1e42623230c937ac8c17571614d74eaf9078033c (latest as of this report)

**Comment by vanyossi** [comment]
Thanks! However I cannot reproduce with the xcf I have. You can send sample files to ghevan@gmail.com

The problem seems to be that "h" is not declared as a valid value (or at all). this is set on line  455
maybe changing the "2" in " [readFileHead $i 2] " to 10 might help with this issue. However unlikely.

**Comment by 0ion9** [comment]
No, I'm not sure what happened here.. maybe a temporary dependency problem?? Anyway, I can't reproduce this any more.
