### ISSUE TITLE
Calligraconverter no longer supports kra and ora files

### ISSUE THREAD

**Issue by 0ion9** [vanyossi/artscript#87]
I recently created this bug: https://bugs.kde.org/show_bug.cgi?id=350495

The maintainer of Krita, Boudwijn Rempt, has just replied:

> Thanks for your report. I'm sorry, but calligraconverter no longer can handle
> .kra and .ora files. It only handles calligra files now. The new way is to use
> krita directly:
> 
> krita bla.kra --export --export-filename=bla.png

If this is the case, then calligraconverter will become unsuitable for artscript's use once the next major release is out.

**Comment by Deevad** [comment]
Hey David, 

Yes, @vanyossi added a switch about it on April ; https://github.com/vanyossi/artscript/commit/28fb6d8e5a8cb2ce9e5c4d3194c857753338c578 . I guess a problem is when calligraconverter ( for calligra suit ) is installed aside Krita now. Artscript will try to rely on this case to calligraconverter with unmaintained KRA/ORA support.  Keeping calligraconverter as a first option was good for retrocompatibility ( Krita 2.8 and before ) , but Krita 2.9 didn't replaced calligraconverter. Calligraconverter still exist, and now handle Calligra 'office' type documents only.  

I don't test newer artscript 2.x ;  I still use here a customised version of Artscript 1.x daily and ported the calligraconverter to krita around April too. I never adapted to use newer artscript 2 ;tabs made me do extra click to do the same job than artscript 1, too bad :)

**Comment by vanyossi** [comment]
Hey david!

So you are having issues with artscript 1?

Enviado desde mi iPad

**Comment by 0ion9** [comment]
@vanyossi : assuming you are talking to me and not David *Revoy*, no, I only use artscript 2. But the increasing troubles with artscript I have been having (especially, detecting the wrong image size for large XCFs and consequently generating distorted output images), are leading me to think maybe I should write my own version.

**Comment by vanyossi** [comment]
@0ion9 Current artscript 2 master should work with latest krita release as it uses krita --export by default. However if something changed in the last month then there could be issues. (I havne't done test this last month because of work related activities)

As for wrong XCF output: I need to check this out as the files I been generating seem to behave as expected

Sorry I missed the first message, I'm a little behind mails.

**Comment by vanyossi** [comment]
@0ion9 Made a fix for the calligraconverter bug. Artscript simply won't use calligraconverter anymore. Older Krita versions would need older artscript versions.

Now onto the XCF problem...

**Comment by vanyossi** [comment]
Closing
