### ISSUE TITLE
 unrecognized image filter "LanczosRadius"

### ISSUE THREAD

**Issue by cg-cnu** [vanyossi/artscript#89]
Platform: CentOS Linux release 7.1.1503 (Core)
ImageMagick: 6.7.8-9 2014-06-10 Q16 

Cloned the repo and did a setup;
Got the below error on trying to resize.
`convert: unrecognized image filter "LanczosRadius" @ error/convert.c/ConvertImageCommand/1493.`
For now, went ahead and chaged the filter to Lanczos and the tool is working fine. 
Any reason its not able to recognize 'LanczosRadius' ?

**Comment by Deevad** [comment]
Hey, 
I think your version of Imagemagick is really old ; probably a side effect of choosing CentOS as a distro ( for sure, it has pros for stability ). 
This option for Lanczos was added in 6.8.

> EWA Lanczos Radius 3 (-filter LanczosRadius) is a recent addition to ImageMagick (version 6.8.0-2). See the Recommended Upsampling Methods (Enlarging) section below for code (with one "fancy parameter") that reproduces this filter with older ImageMagick releases

( quote from http://www.imagemagick.org/Usage/filter/nicolas/ )

**Comment by cg-cnu** [comment]
Hey @Deevad,
Thanks for conforming. For now will just use "Lanzos" as the filter. Cheers.
